env:
  node: true
extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
  - "prettier"
plugins:
  - import
  - jest
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: 0
  import/extensions: 0
  linebreak-style: ["error", "unix"]
  no-underscore-dangle: 0
  object-curly-newline: "off"
